In [1]:
print("Hello World")

Hello World

In [111]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv("loan-train.csv")

In [ ]:
df.head(15)

     Loan_ID Gender Married  ... Credit_History Property_Area Loan_Status
0   LP001002   Male      No  ...            1.0         Urban           Y
1   LP001003   Male     Yes  ...            1.0         Rural           N
2   LP001005   Male     Yes  ...            1.0         Urban           Y
3   LP001006   Male     Yes  ...            1.0         Urban           Y
4   LP001008   Male      No  ...            1.0         Urban           Y
5   LP001011   Male     Yes  ...            1.0         Urban           Y
6   LP001013   Male     Yes  ...            1.0         Urban           Y
7   LP001014   Male     Yes  ...            0.0     Semiurban           N
8   LP001018   Male     Yes  ...            1.0         Urban           Y
9   LP001020   Male     Yes  ...            1.0     Semiurban           N
10  LP001024   Male     Yes  ...            1.0         Urban           Y
11  LP001027   Male     Yes  ...            1.0         Urban           Y
12  LP001028   Male     Yes  ...            1.0         Urban           Y
13  LP001029   Male      No  ...            1.0         Rural           N
14  LP001030   Male     Yes  ...            1.0         Urban           Y

[15 rows x 13 columns]

In [ ]:
#df1.head(10)

    Loan_ID  Gender Married  ... Loan_Amount_Term Credit_History Property_Area
0  LP001015    Male     Yes  ...            360.0            1.0         Urban
1  LP001022    Male     Yes  ...            360.0            1.0         Urban
2  LP001031    Male     Yes  ...            360.0            1.0         Urban
3  LP001035    Male     Yes  ...            360.0            NaN         Urban
4  LP001051    Male      No  ...            360.0            1.0         Urban
5  LP001054    Male     Yes  ...            360.0            1.0         Urban
6  LP001055  Female      No  ...            360.0            1.0     Semiurban
7  LP001056    Male     Yes  ...            360.0            0.0         Rural
8  LP001059    Male     Yes  ...            240.0            1.0         Urban
9  LP001067    Male      No  ...            360.0            1.0     Semiurban

[10 rows x 12 columns]

In [47]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [85]:
num_cols = ['LoanAmount', 'Loan_Amount_Term']
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [86]:
cat_cols = ['Gender', 'Married', 'Dependents', 'Self_Employed']

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [87]:
df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].mode()[0])

In [19]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    str
 1   Gender             356 non-null    str
 2   Married            367 non-null    str
 3   Dependents         357 non-null    str
 4   Education          367 non-null    str
 5   Self_Employed      344 non-null    str
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    str
dtypes: float64(3), int64(2), str(7)
memory usage: 34.5 KB

In [88]:
df['Dependents'] = df['Dependents'].replace('3+', 3)
df['Dependents'] = df['Dependents'].astype(int)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             614 non-null    str
 2   Married            614 non-null    str
 3   Dependents         614 non-null    int64
 4   Education          614 non-null    str
 5   Self_Employed      614 non-null    str
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    str
 12  Loan_Status        614 non-null    str
dtypes: float64(4), int64(2), str(7)
memory usage: 62.5 KB

In [89]:
df.drop('Loan_ID', axis=1, inplace=True)

In [53]:
df.head(5)

  Gender Married  Dependents  ... Credit_History Property_Area  Loan_Status
0   Male      No           0  ...            1.0         Urban            Y
1   Male     Yes           1  ...            1.0         Rural            N
2   Male     Yes           0  ...            1.0         Urban            Y
3   Male     Yes           0  ...            1.0         Urban            Y
4   Male      No           0  ...            1.0         Urban            Y

[5 rows x 12 columns]

In [90]:
df['Total_Income'] = df['ApplicantIncome'] + df['CoapplicantIncome']

In [44]:
df.head(5)

   Dependents  ApplicantIncome  ...  Property_Area_Semiurban  Property_Area_Urban
0           0             5849  ...                    False                 True
1           1             4583  ...                    False                False
2           0             3000  ...                    False                 True
3           0             2583  ...                    False                 True
4           0             6000  ...                    False                 True

[5 rows x 14 columns]

In [91]:
df['Loan_Status'] = df['Loan_Status'].map({'Y':1, 'N':0})
df['Married'] = df['Married'].map({'Yes':1, 'No':0})
df['Self_Employed'] = df['Self_Employed'].map({'Yes':1, 'No':0})
# df['Education'] = df['Education'].map({'Graduate':1, 'Not Graduate':0})

In [93]:
df['Education'].unique()

<StringArray>
['Graduate', 'Not Graduate']
Length: 2, dtype: str

In [94]:
df['Education'] = df['Education'].str.strip()
df['Education'] = df['Education'].map({'Graduate':1, 'Not Graduate':0})

In [95]:
df.head(10)

  Gender  Married  Dependents  ...  Property_Area  Loan_Status  Total_Income
0   Male        0           0  ...          Urban            1        5849.0
1   Male        1           1  ...          Rural            0        6091.0
2   Male        1           0  ...          Urban            1        3000.0
3   Male        1           0  ...          Urban            1        4941.0
4   Male        0           0  ...          Urban            1        6000.0
5   Male        1           2  ...          Urban            1        9613.0
6   Male        1           0  ...          Urban            1        3849.0
7   Male        1           3  ...      Semiurban            0        5540.0
8   Male        1           2  ...          Urban            1        5532.0
9   Male        1           1  ...      Semiurban            0       23809.0

[10 rows x 13 columns]

In [98]:
#one-hot encoding
# df = pd.get_dummies(df, columns=['Property_Area'], drop_first=True)
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(drop='first'), ['Property_Area'])
    ],
    remainder='passthrough'
)

df_transformed = ct.fit_transform(df)

In [59]:
df.head(15)

   Gender Married  ...  Property_Area_Semiurban Property_Area_Urban
0    Male      No  ...                    False                True
1    Male     Yes  ...                    False               False
2    Male     Yes  ...                    False                True
3    Male     Yes  ...                    False                True
4    Male      No  ...                    False                True
5    Male     Yes  ...                    False                True
6    Male     Yes  ...                    False                True
7    Male     Yes  ...                     True               False
8    Male     Yes  ...                    False                True
9    Male     Yes  ...                     True               False
10   Male     Yes  ...                    False                True
11   Male     Yes  ...                    False                True
12   Male     Yes  ...                    False                True
13   Male      No  ...                    False               False
14   Male     Yes  ...                    False                True

[15 rows x 14 columns]

In [99]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [100]:
df.head(10)

  Gender  Married  Dependents  ...  Property_Area  Loan_Status  Total_Income
0   Male        0           0  ...          Urban            1        5849.0
1   Male        1           1  ...          Rural            0        6091.0
2   Male        1           0  ...          Urban            1        3000.0
3   Male        1           0  ...          Urban            1        4941.0
4   Male        0           0  ...          Urban            1        6000.0
5   Male        1           2  ...          Urban            1        9613.0
6   Male        1           0  ...          Urban            1        3849.0
7   Male        1           3  ...      Semiurban            0        5540.0
8   Male        1           2  ...          Urban            1        5532.0
9   Male        1           1  ...      Semiurban            0       23809.0

[10 rows x 13 columns]

In [101]:
df = pd.get_dummies(df, columns=['Gender', 'Property_Area'], drop_first=True)

In [102]:
df.head(10)

   Married  Dependents  ...  Property_Area_Semiurban  Property_Area_Urban
0        0           0  ...                    False                 True
1        1           1  ...                    False                False
2        1           0  ...                    False                 True
3        1           0  ...                    False                 True
4        0           0  ...                    False                 True
5        1           2  ...                    False                 True
6        1           0  ...                    False                 True
7        1           3  ...                     True                False
8        1           2  ...                    False                 True
9        1           1  ...                     True                False

[10 rows x 14 columns]

In [103]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [104]:
df.head(10)

   Married  Dependents  ...  Property_Area_Semiurban  Property_Area_Urban
0        0           0  ...                        0                    1
1        1           1  ...                        0                    0
2        1           0  ...                        0                    1
3        1           0  ...                        0                    1
4        0           0  ...                        0                    1
5        1           2  ...                        0                    1
6        1           0  ...                        0                    1
7        1           3  ...                        1                    0
8        1           2  ...                        0                    1
9        1           1  ...                        1                    0

[10 rows x 14 columns]

In [105]:
df.drop(['ApplicantIncome', 'CoapplicantIncome'], axis=1, inplace=True)

In [106]:
df.head(10)

   Married  Dependents  ...  Property_Area_Semiurban  Property_Area_Urban
0        0           0  ...                        0                    1
1        1           1  ...                        0                    0
2        1           0  ...                        0                    1
3        1           0  ...                        0                    1
4        0           0  ...                        0                    1
5        1           2  ...                        0                    1
6        1           0  ...                        0                    1
7        1           3  ...                        1                    0
8        1           2  ...                        0                    1
9        1           1  ...                        1                    0

[10 rows x 12 columns]

In [108]:
df.to_csv('loan-cleaned.csv', index=False)

In [110]:
X = df.drop('Loan_Status', axis=1)
y = df['Loan_Status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [112]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [139]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

models = {
    "Logistic Regression": LogisticRegression(class_weight='balanced', max_iter=3000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC()
}

In [140]:
from sklearn.metrics import accuracy_score

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    acc = accuracy_score(y_test, preds)
    results[name] = acc
    print(f"{name}: {acc:.4f}")

Logistic Regression: 0.7642
Decision Tree: 0.6911
Random Forest: 0.7561
SVM: 0.6423

In [141]:
print("\nBest Model:", max(results, key=results.get))

Best Model: Logistic Regression

In [142]:
from sklearn.metrics import classification_report

for name, model in models.items():
    preds = model.predict(X_test)
    print(f"\n{name}")
    print(classification_report(y_test, preds))

Logistic Regression
              precision    recall  f1-score   support

           0       0.73      0.51      0.60        43
           1       0.77      0.90      0.83        80

    accuracy                           0.76       123
   macro avg       0.75      0.71      0.72       123
weighted avg       0.76      0.76      0.75       123


Decision Tree
              precision    recall  f1-score   support

           0       0.56      0.56      0.56        43
           1       0.76      0.76      0.76        80

    accuracy                           0.69       123
   macro avg       0.66      0.66      0.66       123
weighted avg       0.69      0.69      0.69       123


Random Forest
              precision    recall  f1-score   support

           0       0.78      0.42      0.55        43
           1       0.75      0.94      0.83        80

    accuracy                           0.76       123
   macro avg       0.77      0.68      0.69       123
weighted avg       0.76      0.76      0.73       123


SVM
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        43
           1       0.65      0.99      0.78        80

    accuracy                           0.64       123
   macro avg       0.32      0.49      0.39       123
weighted avg       0.42      0.64      0.51       123

In [143]:
from sklearn.model_selection import cross_val_score

for name, model in models.items():
    scores = cross_val_score(model, X, y, cv=5)
    print(f"{name}: {scores.mean():.4f}")

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 3000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=3000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 3000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=3000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression: 0.7589
Decision Tree: 0.7150
Random Forest: 0.7769
SVM: 0.6840

In [144]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

log_model = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(class_weight='balanced', max_iter=3000))
])

log_model.fit(X_train, y_train)
preds = log_model.predict(X_test)

from sklearn.metrics import accuracy_score
print("Logistic Regression:", accuracy_score(y_test, preds))

Logistic Regression: 0.7642276422764228

In [145]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    min_samples_split=5,
    random_state=42
)

rf.fit(X_train, y_train)
preds = rf.predict(X_test)

print("Random Forest (tuned):", accuracy_score(y_test, preds))

Random Forest (tuned): 0.7886178861788617

In [146]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(log_model, X, y, cv=5)
print(scores.mean())

0.7588697854191657

In [149]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, preds)
print(cm)

[[18 25]
 [ 1 79]]

In [138]:
from sklearn.metrics import classification_report

print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.95      0.42      0.58        43
           1       0.76      0.99      0.86        80

    accuracy                           0.79       123
   macro avg       0.85      0.70      0.72       123
weighted avg       0.83      0.79      0.76       123

In [148]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    class_weight='balanced',
    random_state=42
)

rf.fit(X_train, y_train)
preds_rf = rf.predict(X_test)
print("Random Forest (tuned):", accuracy_score(y_test, preds))

Random Forest (tuned): 0.7886178861788617

In [150]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ('scaler', StandardScaler()),
    ('clf', LogisticRegression(class_weight='balanced', max_iter=3000))
])

model.fit(X_train, y_train)
preds = model.predict(X_test)

In [151]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, preds))
print(classification_report(y_test, preds))

[[22 21]
 [ 8 72]]
              precision    recall  f1-score   support

           0       0.73      0.51      0.60        43
           1       0.77      0.90      0.83        80

    accuracy                           0.76       123
   macro avg       0.75      0.71      0.72       123
weighted avg       0.76      0.76      0.75       123

In [152]:
probs = model.predict_proba(X_test)[:,1]
preds = (probs > 0.6).astype(int)

In [153]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ('scaler', StandardScaler()),
    ('clf', LogisticRegression(class_weight='balanced', C=0.5 , max_iter=3000))
])

model.fit(X_train, y_train)
preds = model.predict(X_test)

In [154]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, preds))
print(classification_report(y_test, preds))

[[22 21]
 [ 8 72]]
              precision    recall  f1-score   support

           0       0.73      0.51      0.60        43
           1       0.77      0.90      0.83        80

    accuracy                           0.76       123
   macro avg       0.75      0.71      0.72       123
weighted avg       0.76      0.76      0.75       123

In [156]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    scale_pos_weight = len(y_train[y_train==0]) / len(y_train[y_train==1]),
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    random_state=42
)

xgb.fit(X_train, y_train)
preds = xgb.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report

print("XGBoost Accuracy:", accuracy_score(y_test, preds))
print(classification_report(y_test, preds))

XGBoost Accuracy: 0.7235772357723578
              precision    recall  f1-score   support

           0       0.61      0.58      0.60        43
           1       0.78      0.80      0.79        80

    accuracy                           0.72       123
   macro avg       0.70      0.69      0.69       123
weighted avg       0.72      0.72      0.72       123

In [157]:
from lightgbm import LGBMClassifier

lgb = LGBMClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)

lgb.fit(X_train, y_train)
preds = lgb.predict(X_test)

print("LightGBM Accuracy:", accuracy_score(y_test, preds))

[LightGBM] [Info] Number of positive: 342, number of negative: 149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000452 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 286
[LightGBM] [Info] Number of data points in the train set: 491, number of used features: 11
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.696538 -> initscore=0.830864
[LightGBM] [Info] Start training from score 0.830864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
LightGBM Accuracy: 0.7886178861788617