In [1]:
print("Hello World")

Hello World

In [ ]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Titanic-cleaned.csv")

In [4]:
df.head(10)

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Has_Cabin
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0
5,5,6,0,3,"Moran, Mr. James",male,24.0,0,0,330877,8.4583,Q,0
6,6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S,1
7,7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S,0
8,8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S,0
9,9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,0

In [6]:
#Feature Interaction

df['family_size'] = df['SibSp']+df['Parch']+1
df["fare_per_person"] = df["Fare"] / df["family_size"]

In [7]:
df.head(10)

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Has_Cabin,family_size,fare_per_person
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0,2,3.62500
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1,2,35.64165
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0,1,7.92500
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1,2,26.55000
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0,1,8.05000
5,5,6,0,3,"Moran, Mr. James",male,24.0,0,0,330877,8.4583,Q,0,1,8.45830
6,6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S,1,1,51.86250
7,7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S,0,5,4.21500
8,8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S,0,3,3.71110
9,9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,0,2,15.03540

In [8]:
#Aggregation Features to calculate average mean

df["avg_age_class"] = df.groupby("Pclass")["Age"].transform("mean")

In [12]:
df["avg_age_class"].head(10).round()

0    25.0
1    38.0
2    25.0
3    38.0
4    25.0
5    25.0
6    38.0
7    25.0
8    25.0
9    30.0
Name: avg_age_class, dtype: float64

In [13]:
#average fare price 
df["avg_fare_class"] = df.groupby("Pclass")["Fare"].transform("mean")

In [14]:
df["avg_fare_class"].head(10).round()

0    14.0
1    84.0
2    14.0
3    84.0
4    14.0
5    14.0
6    84.0
7    14.0
8    14.0
9    21.0
Name: avg_fare_class, dtype: float64

In [17]:
#Age group feature

df["age_group"] = pd.cut(df["Age"],bins=[0,12,18,60,100],labels=["Child","Teen","Adult","Senior"])

In [18]:
df["age_group"].head(10)

0    Adult
1    Adult
2    Adult
3    Adult
4    Adult
5    Adult
6    Adult
7    Child
8    Adult
9     Teen
Name: age_group, dtype: category
Categories (4, str): ['Child' < 'Teen' < 'Adult' < 'Senior']

In [24]:
#retail sales dataset to perform rolling statistics

df = pd.read_csv("retail_sales_dataset.csv")

In [25]:
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

In [26]:
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [28]:
df['Date'] = pd.to_datetime(df['Date'])

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   datetime64[us]
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: datetime64[us](1), int64(5), str(3)
memory usage: 70.4 KB

In [23]:
df['Date'].head()

0   2023-11-24
1   2023-02-27
2   2023-01-13
3   2023-05-21
4   2023-05-06
Name: Date, dtype: datetime64[us]

In [30]:
df = df.sort_values("Date")

In [40]:
df["year"] = df["Date"].dt.year
df["month"] = df["Date"].dt.month
df["day"] = df["Date"].dt.day
df["weekday"] = df["Date"].dt.weekday

In [41]:
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,rolling_7day_sales,year,month,day,weekday
521,522,2023-01-01,CUST522,Male,46,Beauty,3,500,1500,NaN,2023,1,1,6
179,180,2023-01-01,CUST180,Male,41,Clothing,3,300,900,NaN,2023,1,1,6
558,559,2023-01-01,CUST559,Female,40,Clothing,4,300,1200,NaN,2023,1,1,6
302,303,2023-01-02,CUST303,Male,19,Electronics,3,30,90,NaN,2023,1,2,0
978,979,2023-01-02,CUST979,Female,19,Beauty,1,25,25,NaN,2023,1,2,0
162,163,2023-01-02,CUST163,Female,64,Clothing,3,50,150,NaN,2023,1,2,0
420,421,2023-01-02,CUST421,Female,37,Clothing,3,500,1500,766.428571,2023,1,2,0
609,610,2023-01-03,CUST610,Female,26,Beauty,2,300,600,637.857143,2023,1,3,1
682,683,2023-01-04,CUST683,Male,38,Beauty,2,500,1000,652.142857,2023,1,4,2
230,231,2023-01-04,CUST231,Female,23,Clothing,3,50,150,502.142857,2023,1,4,2

In [42]:
df["rolling_7day_sales"] = df["Total Amount"].rolling(7).mean()

In [44]:
df["rolling_max_sales"] = df["Total Amount"].rolling(7).max()

In [45]:
df["rolling_sales_std"] = df["Total Amount"].rolling(7).std()

In [46]:
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,rolling_7day_sales,year,month,day,weekday,rolling_max_sales,rolling_sales_std
521,522,2023-01-01,CUST522,Male,46,Beauty,3,500,1500,NaN,2023,1,1,6,NaN,NaN
179,180,2023-01-01,CUST180,Male,41,Clothing,3,300,900,NaN,2023,1,1,6,NaN,NaN
558,559,2023-01-01,CUST559,Female,40,Clothing,4,300,1200,NaN,2023,1,1,6,NaN,NaN
302,303,2023-01-02,CUST303,Male,19,Electronics,3,30,90,NaN,2023,1,2,0,NaN,NaN
978,979,2023-01-02,CUST979,Female,19,Beauty,1,25,25,NaN,2023,1,2,0,NaN,NaN
162,163,2023-01-02,CUST163,Female,64,Clothing,3,50,150,NaN,2023,1,2,0,NaN,NaN
420,421,2023-01-02,CUST421,Female,37,Clothing,3,500,1500,766.428571,2023,1,2,0,1500.0,667.000214
609,610,2023-01-03,CUST610,Female,26,Beauty,2,300,600,637.857143,2023,1,3,1,1500.0,583.551320
682,683,2023-01-04,CUST683,Male,38,Beauty,2,500,1000,652.142857,2023,1,4,2,1500.0,592.198286
230,231,2023-01-04,CUST231,Female,23,Clothing,3,50,150,502.142857,2023,1,4,2,1500.0,562.537829